modLoader="javafml"
loaderVersion="[39,)"
license="MIT"
[[mods]]
modId="slaviccraft"
version="${file.jarVersion}"
displayName="Book of Veles"
logoFile="pack.png"
credits="Slavic Mod"
authors="Veles"
description='''
Mod for various Slavic things
'''

[[dependencies.slaviccarft]] 
    modId="forge"
    mandatory=true
    versionRange="[39,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.slaviccarft]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.1,1.19)"
    ordering="NONE"
    side="BOTH"