modLoader="javafml"
loaderVersion="[39,)"
license="MIT"
[[mods]]
modId="slaviccraft"
version="${file.jarVersion}"
displayName="Idolatry"
logoFile="logo.png"
credits="Slavic Mod"
authors="Veles"
description='''
A tutorial mod by Cy4.
'''

[[dependencies.tutorialmod]] 
    modId="forge"
    mandatory=true
    versionRange="[39,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.tutorialmod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.1,1.19)"
    ordering="NONE"
    side="BOTH"